# Generated by Django 4.2.8 on 2023-12-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='transition_time',
            field=models.IntegerField(max_length=100, verbose_name='Время перехода'),
        ),
    ]
