# Generated by Django 4.2.8 on 2023-12-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0002_alter_service_transition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='transition_time',
            field=models.IntegerField(verbose_name='Время перехода'),
        ),
    ]
