# Generated by Django 4.2.8 on 2023-12-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0003_alter_service_transition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='transition_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время перехода'),
        ),
    ]
