# Generated by Django 4.2.7 on 2023-11-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0003_remove_request_moderator_remove_requestservice_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestservice',
            table='RequestService',
        ),
    ]
