# Generated by Django 4.2.7 on 2023-12-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0004_alter_service_transition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='transition_time',
            field=models.CharField(blank=True, null=True, verbose_name='Время перехода'),
        ),
    ]
