# Generated by Django 4.2.7 on 2023-11-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0004_alter_requestservice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestservice',
            table='requestservice',
        ),
    ]
