# Generated by Django 4.2.7 on 2023-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0005_alter_requestservice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='buildings',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
