# Generated by Django 4.2.8 on 2024-01-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0007_alter_service_transition_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='transition_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время перехода'),
        ),
    ]
