# Generated by Django 4.2.7 on 2023-11-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0008_service_buildings_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='buildings_1',
        ),
    ]
