# Generated by Django 4.2.8 on 2024-01-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0008_requestservice_transition_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestservice',
            name='transition_time',
        ),
    ]
