# Generated by Django 4.2.8 on 2023-12-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0010_remove_service_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
