# Generated by Django 4.2.8 on 2024-01-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0010_request_transition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='buildings',
            field=models.CharField(max_length=200, verbose_name='Фото строений'),
        ),
        migrations.AlterField(
            model_name='service',
            name='transition',
            field=models.CharField(max_length=200, verbose_name='Фото маршрута'),
        ),
    ]
