# Generated by Django 4.2.8 on 2024-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0011_alter_service_buildings_alter_service_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='formation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
