# Generated by Django 4.2.7 on 2024-01-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0012_applications_applicationsoptions_options_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Черновик'), (2, 'Удален'), (3, 'Сформирован'), (4, 'Завершен'), (5, 'Отклонен')], max_length=100, verbose_name='Статус')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formation_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата формирования')),
                ('completion_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmstu.request', verbose_name='Заявка')),
            ],
            options={
                'db_table': 'requestservice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Маршрут')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('buildings', models.BinaryField(blank=True, null=True, verbose_name='Фото строений')),
                ('transition', models.BinaryField(blank=True, null=True, verbose_name='Фото маршрута')),
                ('transition_time', models.CharField(max_length=100, verbose_name='Время перехода')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'db_table': 'Service',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя')),
                ('userpassword', models.CharField(max_length=100, verbose_name='Пароль')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Модератор ли')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='applicationsoptions',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationsoptions',
            name='option',
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.DeleteModel(
            name='Applicationsoptions',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='requestservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmstu.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='request',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qwerty', to='bmstu.userprofile', verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_user_set', to='bmstu.userprofile', verbose_name='Юзер'),
        ),
    ]
