# Generated by Django 4.2.7 on 2024-01-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0013_request_requestservice_service_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_moderator_set', to='bmstu.userprofile', verbose_name='Модератор'),
        ),
    ]
