# Generated by Django 4.2.8 on 2024-01-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0015_remove_request_created_date_request_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
