# Generated by Django 4.2.8 on 2024-01-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0016_requestservice_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
