# Generated by Django 4.2.8 on 2024-01-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0017_alter_service_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
    ]
